spring:
  profiles:
    active: dev
  banner:
    location: classpath:banner.txt

  r2dbc:
    pool:
      enabled: true

  sql:
    init:
      mode: always

  logging:
        level:
          org.springframework.boot.context.logging.LoggingApplicationListener: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
