name: CI develop (No Docker)

on:
  pull_request:
    branches: [ develop ]    # PR que llegan a develop
  push:
    branches: [ develop ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: ci

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties') }}

      - name: Test & Coverage
        run: ./gradlew test jacocoTestReport

      - name: Upload JaCoCo HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html
