name: CI (No Docker)

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: ci      # usa H2 modo MySQL

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Test & Coverage
        run: ./gradlew test jacocoTestReport

      - name: Validate coverage
        run: |
          COVERAGE=$(grep -Po 'line-rate="\K[\d.]+' build/reports/jacoco/test/jacocoTestReport.xml | head -1)
          echo "Cobertura: $COVERAGE"
          COV_INT=$(echo "$COVERAGE * 100" | bc | cut -d'.' -f1)
          if [ "$COV_INT" -lt 90 ]; then
            echo "❌ Coverage less than 90%"
            exit 1
          else
            echo "✅ sufficient coverage"
          fi


      - name: Upload JaCoCo HTML
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

  deploy:
    needs: test-build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build fat‑jar
        run: ./gradlew bootJar -x test

      - name: Upload JAR to S3
        run: aws s3 cp build/libs/*.jar s3://mi‑bucket/latest.jar

      - name: Restart app on EC2 (SSM)
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Restart app" \
            --parameters commands="sudo systemctl stop bank && aws s3 cp s3://mi‑bucket/latest.jar /opt/bank/bank.jar && sudo systemctl start bank"
